### ISSUE TITLE
user stories for the 3 prototype programs

### ISSUE THREAD

**Issue by kslokhandwala2022** [CS3733-C21-Team-U/CS3733-C21-Team-U-Project-BWApp#14]
**User stories for the 3 Porotype Apps - Not the final healthcare app**

- [ ] User Stories for the Museum DB App (#3)
- [ ] User Stories for the Algo Team App (#12 #4)
- [x] User Stories for the UI Team App (#11)

**Comment by Kohmei358** [comment]
Merge into #13

**Comment by Kohmei358** [comment]
I'm not super sure if the Algo team needs to submit a JAR File or IntelliJ Program. Also there's contradictions on whether the submission is for A* or DFS:

> The A* algorithm IntelliJ project along with your simple map. You do not need to submit the depth-first search pathfinding program.

> Write a depth-first search algorithm and test it on a very simple map with nodes and edges that you create yourselves. Then begin writing the A* algorithm. Although you do not need to complete the A* algorithm in project B, you should get at least part of the algorithm working so you can run it against your map.
