### ISSUE TITLE
Sprint 1 Word Doc

### ISSUE THREAD

**Issue by kslokhandwala2022** [CS3733-C21-Team-U/CS3733-C21-Team-U-Project-BWApp#140]
- [x] Cover Page

WPI CS3733-C21 Software Engineering, Prof. Wong
The title “Project Iteration 1”
Team name
Team coach
List each person, their position, and their GitHub account name. Note: these roles are only until the end of the first development sprint.
GitHub link to your organization. Make sure repositories are viewable to me and to your team coach!
- [x] Your sprint 1 backlog - include a list of this sprint’s user stories with sizing information obtained through the use of the Planning Poker sizing exercise.
- [ ] Your product 1 backlog - include a list of anticipated future user stories and epics.
- [ ] Collection of tasks necessary to implement each of the user stories in your sprint 1 backlog
- [ ] Person(s) responsible for having completed each task
- [x] The initial class diagram and database design (ERD) used by the team at the start of this sprint
- [ ] The actual class diagram and database design (ERD) after this iteration’s implementation 
- [ ] A discussion of why the class diagram and/or ERD changed. This is an important section to fill out so everyone on the team learns how to create better software designs! (DB)
- [ ] Sprint burndown chart and your team velocity (in user story points) only counting user story points for user stories that were completed AND bug free.
- [ ] The salary distribution, $100.00 WPI, with the accompanying mechanism and reasoning using the format from previous submissions.

**Comment by kslokhandwala2022** [comment]
[ ] Cover Page
1. WPI CS3733-C21 Software Engineering, Prof. Wong
2. The title “Project Iteration 1”
3. Team name
5. Team coach
6. List each person, their position, and their GitHub account name. Note: these roles are only until the end of the first development sprint. 
7. GitHub link to your organization. Make sure repositories are viewable to me and to your team coach!

[ ] Your sprint 1 backlog - include a list of this sprint’s user stories with sizing information obtained through the use of the Planning Poker sizing exercise. 
[ ] Your product 1 backlog - include a list of anticipated future user stories and epics.
[ ] Collection of tasks necessary to implement each of the user stories in your sprint 1 backlog
[ ] Person(s) responsible for having completed each task
[ ] The initial class diagram and database design (ERD) used by the team at the start of this sprint
[ ] The actual class diagram and database design (ERD) after this iteration’s implementation
[ ]  A discussion of why the class diagram and/or ERD changed. This is an important section to fill out so everyone on the team learns how to create better software designs!
[ ] Sprint burndown chart and your team velocity (in user story points) only counting user story points for user stories that were completed AND bug free.
[ ] The salary distribution, $100.00 WPI, with the accompanying mechanism and reasoning using the format from previous submissions.
