### ISSUE TITLE
Word Doc with Team info

### ISSUE THREAD

**Issue by kslokhandwala2022** [CS3733-C21-Team-U/CS3733-C21-Team-U-Project-BWApp#15]
- [ ] Cover page
  1. CS3733-C21 Prof. Wong
  2. Team name
  3. Your team coach.
  4. List each person, their position, and their GitHub account name. Note: these roles are only until the end of the first development sprint. 
  5. GitHub link to your organization. Make sure repositories are viewable to me and to your team coach! 

- [ ] List all software, project, and communication tools that the team plans to use.
- [ ] List of user stories for the 3 prototype programs and who worked on them. #14 
- [ ] The functional model for the minimal application. UI mockups are to be pasted as images into the document. #13 
- [ ] Requirements Gathering. Results of your brainstorming, interview protocol (questions and user types), and survey. #10 #5 
- [ ] Mention what you did this past week as a team to promote a healthy and congenial team culture.
- [ ]  deliverable salary of $30.00 WPI dollars
- [ ] Acknowledge significant contributions by your team members in a personal manner
- [ ] Review all work and requirements!

**Comment by Kohmei358** [comment]
- [ ] Cover page
- [ ] List all software, project, and communication tools that the team plans to use.
- [ ] List of user stories for the 3 prototype programs and who worked on them.
- [ ] The functional model for the minimal application. UI mockups are to be pasted as images into the document.
- [ ] Requirements Gathering. Results of your brainstorming, interview protocol (questions and user types), and survey.
- [ ] Mention what you did this past week as a team to promote a healthy and congenial team culture.
- [ ]  deliverable salary of $30.00 WPI dollars
- [ ] Acknowledge significant contributions by your team members in a personal manner
- [ ]

**Comment by Kohmei358** [comment]
What are the "3 Prototype programs"?
