### ISSUE TITLE
Everything we need to submit for Project B

### ISSUE THREAD

**Issue by Kohmei358** [CS3733-C21-Team-U/CS3733-C21-Team-U-Project-BWApp#19]
**The 3 Main Programs**
- [x] **The Xdb JAR file and IntelliJ project** #3 [DB Prototype (access museum DB)]
- [x] **The A \* algorithm IntelliJ project along with your simple map** #12 #9 #4 [A*/DFS Program]
- [x] **Xapp JAR file** #11 [UI Prototype (switch between pages)]

**Non-Code things**
- [ ] Floor map CSV files #18 
- [ ] A single Word Doc (using the Project B upload button) #15

**Comment by Kohmei358** [comment]
I'm not super sure if the Algo team needs to submit a JAR File or IntelliJ Program. Also there's contradictions on whether the submission is for A* or DFS:

> The A* algorithm IntelliJ project along with your simple map. You do not need to submit the depth-first search pathfinding program.

> Write a depth-first search algorithm and test it on a very simple map with nodes and edges that you create yourselves. Then begin writing the A* algorithm. Although you do not need to complete the A* algorithm in project B, you should get at least part of the algorithm working so you can run it against your map.
