### ISSUE TITLE
Document Submission Checklist

### ISSUE THREAD

**Issue by Kohmei358** [CS3733-C21-Team-U/CS3733-C21-Team-U-Project-BWApp#69]
- [ ] Cover page including 
- [ ] WPI CS3733-C21 Software Engineering, Prof. Wong
- [ ] Team name
- [ ] Team coach
- [ ] List each person, their position, and their GitHub account name. Note: these roles are only until the end of the first development sprint. 
- [ ] GitHub link to your organization. Make sure repositories are viewable to me and to your team coach! 
- [ ] Table of Contents
- [ ] Introduction. This should mention the application you will be developing in this course, for whom, and for what purpose.
- [ ] Current system. Research the Faulkner Hospital path finding application. Also, based on your experiences visiting a hospital, how do patients and visitors get directions if no path finding application exists? 
- [ ] Software development environment. List all of the software tools and programming environments your team is currently using, most of which is dictated by the class.
- [ ] Any changes in team positions since Project Part B

- [ ] Indicate what team events were done to improve team bonding.

- [ ] Acknowledge significant contributions by your team members in a personal manner. Allocation of $60 WPI dollars to team members. Justify your rationale and method for the final salary distribution. List the team members and their salary in alphabetical order by last name using the following format:

**Comment by Kohmei358** [comment]
- [ ] Cover page including 
- [ ] WPI CS3733-C21 Software Engineering, Prof. Wong
- [ ] Team name
- [ ] Team coach
- [ ] List each person, their position, and their GitHub account name. Note: these roles are only until the end of the first development sprint. 
- [ ] GitHub link to your organization. Make sure repositories are viewable to me and to your team coach! 
- [ ] Table of Contents
- [ ] Introduction. This should mention the application you will be developing in this course, for whom, and for what purpose.
- [ ] Current system. Research the Faulkner Hospital path finding application. Also, based on your experiences visiting a hospital, how do patients and visitors get directions if no path finding application exists? 
- [ ] Software development environment. List all of the software tools and programming environments your team is currently using, most of which is dictated by the class.
- [ ] Any changes in team positions since Project Part B

- [ ] Indicate what team events were done to improve team bonding.

- [ ] Acknowledge significant contributions by your team members in a personal manner. Allocation of $60 WPI dollars to team members. Justify your rationale and method for the final salary distribution. List the team members and their salary in alphabetical order by last name using the following format:
